### ISSUE TITLE
Ability to add documents( .json files)

### ISSUE THREAD

**Issue by rchandran7** [CS180-spring/cs180-23-thedreamteam#21]

**Comment by paulian7** [comment]
📍 Actionable task of user story #2

**Comment by kliang622** [comment]
### Test Cases: 

1. Given an empty document, when uploading to the database, then the response should give an error saying "error: document is empty".
2. Given a document with content inside, when uploading to the database, then the response should upload successfully. 
3. Given no document, when to the database, there should be an error given. 
4. Given an invalid file path to upload a document, when uploading to the database, then the response should say that the path is invalid.
