### ISSUE TITLE
Inability to add a invalid file type

### ISSUE THREAD

**Issue by rchandran7** [CS180-spring/cs180-23-thedreamteam#25]
A warning is presented to the user when they try to upload the incorrect file type. All file types uploaded / added to the database must be .json files.

**Comment by paulian7** [comment]
📍 Actionable task of user story #2

**Comment by kliang622** [comment]
### Test Cases

1. Given file that is not a JSON file, when adding it to the database, the program will print an error telling user that the file type is invalid
