### ISSUE TITLE
ability to delete .json files from database

### ISSUE THREAD

**Issue by kliang622** [CS180-spring/cs180-23-thedreamteam#30]

**Comment by paulian7** [comment]
📍 Actionable task of user story #2

**Comment by kliang622** [comment]
### Test Cases: 

1. Given an empty database, when attempting to delete a file/(s), then the response should give an error saying "error: database is empty".
2. Given a collection with files, when attempting to delete the file from the collection, then the file should be deleted from the collection successfully 
3. Given a collection with or without files, when attempting to delete an inexistant file from the collection, then it should point to an error saying that the file does not exist.
