### ISSUE TITLE
Searching for existing items in the database.

### ISSUE THREAD

**Issue by kliang622** [CS180-spring/cs180-23-thedreamteam#31]

**Comment by paulian7** [comment]
📍 Actionable task of user story #10

**Comment by kliang622** [comment]
### Test Cases
1. Given an existing file in a database, when searching for a file, then the program will print out the contents of the file
2. Given an inexistent file in the database, when searching for a file, then the program will print an error saying that the contents do not exist in the collection
3. Given a database, when searching through an inexisting collection, then the program will print an error saying that the collection does not exist.
