### ISSUE TITLE
Cover edge cases for menu functionality

### ISSUE THREAD

**Issue by kliang622** [CS180-spring/cs180-23-thedreamteam#42]
- Aim is to make things more user friendly :)
- Aim to include more directions on how to use the program

**Comment by paulian7** [comment]
📍 Actionable task of user story #7

**Comment by paulian7** [comment]
## Test Cases 
- When the program runs on the terminal, the user should be greeted with a menu that prompts them to input any number correlating to the task they want to do to the database. If the user inputs an incorrect or invalid number (such as a negative value), the program should output back that it's not a valid input and to try again.

- If the input is valid, the program should then ask for more information from the user to help execute the option they picked.  If they input an invalid number, the program will once again output back that it's not a valid input and to try again.
