### ISSUE TITLE
ability to edit contents within JSON 

### ISSUE THREAD

**Issue by kliang622** [CS180-spring/cs180-23-thedreamteam#44]
- Given an existing JSON file in the database collection, user should be able to add and delete text from the file and save changes to JSON

Test Cases:

-When a user inputs an invalid json file path within the database, the program should present an error message saying: "[fileName] does not exists within the database!"
- When a user inputs a valid json file path within the database and the edited content parameter does not exist within the file, the program should present an error message: "cannot find this parameter to change within the file!"
- When a user inputs a valid json file path within the database and the edit content parameter does exist within the file, the program should successfully modify the contents.

**Comment by paulian7** [comment]
📍 Actionable task of user story #3
