### ISSUE TITLE
As a user I want to be able to create an account so that I can interact with the database

### ISSUE THREAD

**Issue by alihshaikh** [CS180-spring/cs180-23-thedreamteam#5]
## Priority
Low

## Story Points
6

## Test Cases
1) The login screen appears
- Given that a user is on the homepage
- When the user clicks on the "login" button on the top right of the screen
- The page navigates to the login screen
- If the page fails to navigate to the login screen, an error textbox will appear in the middle of the screen stating: "Could not navigate to login page"
2) The user can login at the login screen
- Given that the user has already navigated to the login screen
- When the user inputs their username and password into the "Username" and "Password" fields
- The login page navigates to the files page and the "login" button is replaced with the user's username
- If the login fails, an error textbox will appear in the center of screen stating: "Could not login"

**Comment by NateTran** [comment]
Tasks:
1) Create login screen
2) Create login authentication in the backend

**Comment by kliang622** [comment]
No longer doing this feature
